### ISSUE TITLE
Compile Error?

### ISSUE THREAD

**Issue by ghost** [sieren/blidino#1]
New to Arduino but not to coding.  Using Arduino IDE 1.6.1

After following installation instructions,  I get the following error when I compile nRF51822-BLEMIDI.ino.

```

/Users/xxx/Documents/Arduino/libraries/USB_Host_Shield_20/Usb.h:36:0,
                 from nRF51822-BLEMIDI.ino:31:
/Users/xxx/Documents/Arduino/libraries/USB_Host_Shield_20/usbhost.h: In static member function 'static void SPi<SPI_CLK, SPI_MOSI, SPI_MISO, SPI_SS>::init()':
/Users/xxx/Documents/Arduino/libraries/USB_Host_Shield_20/usbhost.h:50:21: error: 'class SPIClass' has no member named 'setClockDivider'
                 SPI.setClockDivider(4); // Set speed to 84MHz/4=21MHz - the MAX3421E can handle up to 26MHz
                     ^
Error compiling.
```

An examination of 

```
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/RBL_nRF51822/libraries/SPI/SPI.h
```

shows that indeed, there is no member named 'setClockDivider'.

Not sure how to proceed, any help appreciated.

**Comment by sieren** [comment]
Hey, I just checked and apprently the USB Host Shield library has been updated in the meantime. There's a slim chance something might be broken. I will have a look into that sometime next week.
In the meantime, try using my fork (which once was merged to the main branch):
https://github.com/sieren/USB_Host_Shield_2.0

**Comment by ghost** [comment]
Thanks for the tip. That did the trick!

**Comment by sieren** [comment]
Thanks for bringing this up though :)
I'll have a look and see if I can fix it on the main library. Gonna leave this open till then as a reminder for myself and others encountering this issue.

**Comment by sieren** [comment]
I've fixed this now and issued a Pull Request to the master branch:
https://github.com/felis/USB_Host_Shield_2.0/pull/156

Thanks again for reporting!

**Comment by sieren** [comment]
FYI: https://github.com/sieren/blidino/pull/8
