### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by popcornell** [sieren/blidino#10]
Hi, i am using Arduino IDE 1.6.8, i followed all the instructions in the README.md but somewhat 
i still i get a compilation error. Maybe i am doing something wrong.
I think i've installed correctly the readbearlab library because i can get working the examples.
I've seen also the previous issues reported to no avail, especially the last which was a compiling issue too. It was fixed wasn't it ? 

Thank you very much for your work 
Samuele

*_Error report : *_

Arduino: 1.6.8 (Windows 10), Board: "RBL nRF51822(V1.5 32KB)"

In file included from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:23:0:

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:24:13: error: expected unqualified-id before numeric constant

 #define D16 16

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:35:14: note: in expansion of macro 'D16'

 #define SCK  D16

```
          ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/nrf51.h:159:18: note: in expansion of macro 'SCK'

   __IO uint32_t  SCK;                               /*!< Pin select for SCK.                                                   */

```
              ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:26:13: error: expected unqualified-id before numeric constant

 #define D18 18

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:37:14: note: in expansion of macro 'D18'

 #define MOSI D18

```
          ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/nrf51.h:160:18: note: in expansion of macro 'MOSI'

   __IO uint32_t  MOSI;                              /*!< Pin select for MOSI.                                                  */

```
              ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:25:13: error: expected unqualified-id before numeric constant

 #define D17 17

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:36:14: note: in expansion of macro 'D17'

 #define MISO D17

```
          ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/nrf51.h:161:18: note: in expansion of macro 'MISO'

   __IO uint32_t  MISO;                              /*!< Pin select for MISO.                                                  */

```
              ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected nested-name-specifier before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:28:32: note: in expansion of macro 'A1'

 template <typename R, typename A1>

```
                            ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected '>' before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:28:32: note: in expansion of macro 'A1'

 template <typename R, typename A1>

```
                            ^
```

In file included from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/SerialBase.h:24:0,

```
             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/RawSerial.h:23,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/mbed.h:51,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\cores\RBL_nRF51822/Arduino.h:13,

             from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:24:
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:35:38: error: expected ',' or '...' before '(' token

```
 FunctionPointerArg1(R (*function)(A1) = 0) {

                                  ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:45:50: error: expected ',' or '...' before '(' token

```
 FunctionPointerArg1(T *object, R (T::*member)(A1)) {

                                              ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:53:30: error: expected ',' or '...' before '(' token

```
 void attach(R (*function)(A1)) {

                          ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:64:42: error: expected ',' or '...' before '(' token

```
 void attach(T *object, R (T::*member)(A1)) {

                                      ^
```

In file included from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:23:0:

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected identifier before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:72:12: note: in expansion of macro 'A1'

```
 R call(A1 a) {

        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected ',' or '...' before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:72:12: note: in expansion of macro 'A1'

```
 R call(A1 a) {

        ^
```

In file included from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/SerialBase.h:24:0,

```
             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/RawSerial.h:23,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/mbed.h:51,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\cores\RBL_nRF51822/Arduino.h:13,

             from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:24:
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:83:20: error: expected ')' before '(' token

```
 R(*get_function(A1))() {

                ^
```

In file included from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:23:0:

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected identifier before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:88:19: note: in expansion of macro 'A1'

```
 R operator ()(A1 a) {

               ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected ',' or '...' before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:88:19: note: in expansion of macro 'A1'

```
 R operator ()(A1 a) {

               ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected identifier before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:97:60: note: in expansion of macro 'A1'

```
 static R membercaller(void *object, uintptr_t *member, A1 a) {

                                                        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected ',' or '...' before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:97:60: note: in expansion of macro 'A1'

```
 static R membercaller(void *object, uintptr_t *member, A1 a) {

                                                        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected identifier before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:104:23: note: in expansion of macro 'A1'

```
     R (*function)(A1); // static function pointer

                   ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected ',' or '...' before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:104:23: note: in expansion of macro 'A1'

```
     R (*function)(A1); // static function pointer

                   ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected identifier before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:108:43: note: in expansion of macro 'A1'

```
 R (*_membercaller)(void*, uintptr_t*, A1); // registered membercaller function to convert back and call _m.member on _object

                                       ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:28:13: error: expected ',' or '...' before numeric constant

 #define D20 20

```
         ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\variants\RBL_nRF51822_32KB/pins_arduino.h:46:12: note: in expansion of macro 'D20'

 #define A1 D20

```
        ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:108:43: note: in expansion of macro 'A1'

```
 R (*_membercaller)(void*, uintptr_t*, A1); // registered membercaller function to convert back and call _m.member on _object

                                       ^
```

In file included from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/SerialBase.h:24:0,

```
             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/RawSerial.h:23,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/mbed.h:51,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\cores\RBL_nRF51822/Arduino.h:13,

             from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:24:
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h: In member function 'void mbed::FunctionPointerArg1<R, <anonymous> >::attach(T_, R T::_)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:66:36: error: expected '>' before '(' token

```
     *reinterpret_cast<R (T::**)(A1)>(_member) = member;

                                ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h: In member function 'R mbed::FunctionPointerArg1<R, <anonymous> >::call(int)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:74:31: error: 'a' was not declared in this scope

```
        return _p.function(a);

                           ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:76:53: error: 'a' was not declared in this scope

```
        return _membercaller(_p.object, _member, a);

                                                 ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h: In member function 'R mbed::FunctionPointerArg1<R, <anonymous> >::operator()(int)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:89:21: error: 'a' was not declared in this scope

```
     return call(a);

                 ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h: In static member function 'static R mbed::FunctionPointerArg1<R, <anonymous> >::membercaller(void_, uintptr_t_, int)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:99:24: error: expected ',' or ';' before '=' token

```
     R (T::**m)(A1) = reinterpret_cast<R (T::**)(A1)>(member);

                    ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:100:25: error: 'a' was not declared in this scope

```
     return (o->**m)(a);

                     ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h: At global scope:

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:114:34: error: type/value mismatch at argument 2 in template parameter list for 'template<class R, int <anonymous> > class mbed::FunctionPointerArg1'

 class FunctionPointerArg1<R, void>{

```
                              ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:114:34: error:   expected a constant of type 'int', got 'void'

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:197:39: error: type/value mismatch at argument 2 in template parameter list for 'template<class R, int <anonymous> > class mbed::FunctionPointerArg1'

 typedef FunctionPointerArg1<void, void> FunctionPointer;

```
                                   ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:197:39: error:   expected a constant of type 'int', got 'void'

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:197:56: error: invalid type in declaration before ';' token

 typedef FunctionPointerArg1<void, void> FunctionPointer;

```
                                                    ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:198:38: error: type/value mismatch at argument 2 in template parameter list for 'template<class R, int <anonymous> > class mbed::FunctionPointerArg1'

 typedef FunctionPointerArg1<void, int> event_callback_t;

```
                                  ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:198:38: error:   expected a constant of type 'int', got 'int'

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/FunctionPointer.h:198:56: error: invalid type in declaration before ';' token

 typedef FunctionPointerArg1<void, int> event_callback_t;

```
                                                    ^
```

In file included from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/RawSerial.h:23:0,

```
             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/mbed.h:51,

             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\cores\RBL_nRF51822/Arduino.h:13,

             from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:24:
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/SerialBase.h: In member function 'void mbed::SerialBase::attach(T_, void (T::_)(), mbed::SerialBase::IrqType)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/SerialBase.h:106:24: error: request for member 'attach' in '((mbed::SerialBase*)this)->mbed::SerialBase::_irq[type]', which is of non-class type 'mbed::FunctionPointer {aka int}'

```
         _irq[type].attach(tptr, mptr);

                    ^
```

In file included from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/mbed.h:55:0,

```
             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\cores\RBL_nRF51822/Arduino.h:13,

             from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:24:
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/Ticker.h: In member function 'void mbed::Ticker::attach_us(void (*)(), timestamp_t)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/Ticker.h:92:19: error: request for member 'attach' in '((mbed::Ticker*)this)->mbed::Ticker::_function', which is of non-class type 'mbed::FunctionPointer {aka int}'

```
     _function.attach(fptr);

               ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/Ticker.h: In member function 'void mbed::Ticker::attach_us(T_, void (T::_)(), timestamp_t)':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/Ticker.h:104:19: error: request for member 'attach' in '((mbed::Ticker*)this)->mbed::Ticker::_function', which is of non-class type 'mbed::FunctionPointer {aka int}'

```
     _function.attach(tptr, mptr);

               ^
```

In file included from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/mbed.h:61:0,

```
             from C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5\cores\RBL_nRF51822/Arduino.h:13,

             from C:\Users\popco\Documents\Arduino\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:24:
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/InterruptIn.h: In member function 'void mbed::InterruptIn::rise(T_, void (T::_)())':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/InterruptIn.h:84:15: error: request for member 'attach' in '((mbed::InterruptIn*)this)->mbed::InterruptIn::_rise', which is of non-class type 'mbed::FunctionPointer {aka int}'

```
     _rise.attach(tptr, mptr);

           ^
```

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/InterruptIn.h: In member function 'void mbed::InterruptIn::fall(T_, void (T::_)())':

C:\Users\popco\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.5/cores/RBL_nRF51822/mbed/api/InterruptIn.h:101:15: error: request for member 'attach' in '((mbed::InterruptIn*)this)->mbed::InterruptIn::_fall', which is of non-class type 'mbed::FunctionPointer {aka int}'

```
     _fall.attach(tptr, mptr);

           ^
```

exit status 1
Error compiling for board RBL nRF51822(V1.5 32KB).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sieren** [comment]
Hey, thanks for the report.
I was able to reproduce this on Windows (but not the other platforms) and deployed a fix.
Apparently the compiler got confused by an unnecessary include (`pin_arduino.h`) which I have removed.

Let me know if this works for you now.

**Comment by popcornell** [comment]
Thank you very much, now it works perfectly .
