### ISSUE TITLE
Arduino board?

### ISSUE THREAD

**Issue by rcrath** [sieren/blidino#12]
Hi, 

Utterly new to this, but want to connect usb midi devices to my iPad via bluetooth and this looks like the answer.   I am assuming that in addition to USB Host Shield 2.0 for Arduino and RedBearLab nRF51822 I need an arduino board of some sort to add them on to, correct?  Is any particular board recommended or required?  I realize this is probably a real basic question, but thanks.

**Comment by sieren** [comment]
Hey, the RedBearLab nRF51822 is an Arduino board in itself, so no additional hardware needed.

**Comment by rcrath** [comment]
@sieren THanks!
