### ISSUE TITLE
Not Pairing?

### ISSUE THREAD

**Issue by davrocks** [sieren/blidino#17]
Sorry for the constant problems, and I'm not sure if this one is in the code. In android Marshmallow, I am sure that midi can be transferred over Bluetooth, as I've seen it done. On my LG G Stylo (bluetooth low energy enabled I think) I can't pair with the BLIDINO under Bluetooth. Another note is that I am not using a battery. Instead, I am using a charge only usb to microusb cable to power the blidino. I've noticed that the LED indicator starts blinking, but stops after a few seconds. During this short period, the BLIDINO shows up under Bluetooth, but my phone can't find the arduino after it stops blinking. Should I get a battery like used in the video and report back? Or is this not a problem?

**Comment by sieren** [comment]
Let me get back to you on this later. I will try and verify this, however using iOS. I have no idea about MIDI/BLE on Android, so far I've only verified the project with OSX/iOS.

**Comment by sieren** [comment]
Tried to reproduce, but to no avail.

Can't pair = it doesnt show up? Pairing fails? 
A little bit more detail please.

Also, it won't start up correctly if you have chosen the wrong board in Arduino.
Assuming you have the nRF51288 Board, there is two versions, try choosing the other one.
