### ISSUE TITLE
hm-10

### ISSUE THREAD

**Issue by stellanhaglund** [sieren/blidino#5]
wouldn't this work with the hm-10?

**Comment by mfk-ableton** [comment]
Nope, at least not out of the box as the HM-10 is using a CC2541 Chip from TI, while the one in this repo is based on the Nordic Semiconductors nRF51288. Trivial to say they both use different SDKs. However it should be fairly easy to port over the code to the CC SDK.

**Comment by sieren** [comment]
Nope, at least not out of the box as the HM-10 is using a CC2541 Chip from TI, while the one in this repo is based on the Nordic Semiconductors nRF51288. Trivial to say they both use different SDKs. However it should be fairly easy to port over the code to the CC SDK.

**Comment by JasonBugeja** [comment]
I wish I could have used the hm-10 in my project https://github.com/JasonBugeja/AccordionMega_USB_Keyb 
However, I don't know where to start to port the code! 

I have managed to use HC-05 and HC-06 for bluetooth connection to Hairless Midi Serial bridge on pc, but my dream is using Midi over Bluetooth LE to connect to IOS.

**Comment by sieren** [comment]
I cant tell from a distance either, what struck me though was this line:
"Super fast reaction rate of 0.4 seconds" [1] which would be 400ms, way above the tolerable limit of approx. 10ms for audio (Possibly related due to the fact it's communication is going through AT)

[1] http://www.ebay.com/itm/HM-10-CC2541-4-0-Bluetooth-to-UART-Transceiver-Module-Transparent-Serial-Port/171503648352

**Comment by JasonBugeja** [comment]
That sounds super-slow, not super-fast! Maybe not even worth trying... HC-06 with Hairless Midi Serial bridge did not have bad latency.  The only issue I had was having to re-pair devices often.

**Comment by sieren** [comment]
Indeed. In addition the HM-10s max Baud Rate seems to be 9600, the MIDI Standard specifies 31250bps. I believe the nRF8001 I used in my early experiments was capped at 9600 as well, which is a show-stopper.

Is there a decent HC-06 BLE Shield for Arduino?
