### ISSUE TITLE
LBM313 Bluetooth LE Compatibility?

### ISSUE THREAD

**Issue by timpulver** [sieren/blidino#6]
Is this compatible with the [LightBlue Bean](http://legacy.punchthrough.com/bean/)?

**Comment by sieren** [comment]
I couldn't find their Bluetooth SDK Documentation.
All I found was http://legacy.punchthrough.com/bean/the-arduino-reference/ and that'd be a definite no (no access to lower-level Bluetooth APIs available).

**Comment by timpulver** [comment]
Too bad, thanks for your quick reply!
