### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Steph77** [sieren/blidino#7]
Hi,
I've got a problem when i try to compile the file with arduino.

I think i didn't miss a thing when reading the README.md file but my english isn't perfect at all...

Do you have an idea of my problem ?

Thank you for your work
Stéphane
This my error report : 

Arduino : 1.6.7 (Windows 10), Carte : "RBL nRF51822(V1.0 16KB)"

In file included from C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/Usb.h:36:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:30:
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In static member function 'static void SPi<SPI_CLK, SPI_MOSI, SPI_MISO, SPI_SS>::init()':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:50:20: error: expected unqualified-id before '.' token

```
             SPI.begin();

                ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:60:20: error: expected unqualified-id before '.' token

```
             SPI.setClockDivider(4); // Set speed to 84MHz/4=21MHz - the MAX3421E can handle up to 26MHz

                ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'void MAX3421e<SPI_SS, INTR>::regWr(uint8_t, uint8_t)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:171:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg | 0x02);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:172:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(data);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'uint8_t\* MAX3421e<SPI_SS, INTR>::bytesWr(uint8_t, uint8_t, uint8_t*)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:211:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg | 0x02);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:213:20: error: expected unqualified-id before '.' token

```
             SPI.transfer(*data_p);

                ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'uint8_t MAX3421e<SPI_SS, INTR>::regRd(uint8_t)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:261:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:262:25: error: expected primary-expression before '.' token

```
     uint8_t rv = SPI.transfer(0); // Send empty byte

                     ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'uint8_t\* MAX3421e<SPI_SS, INTR>::bytesRd(uint8_t, uint8_t, uint8_t*)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:304:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:306:28: error: expected primary-expression before '.' token

```
         *data_p++ = SPI.transfer(0);

                        ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: At global scope:

nRF51822-BLEMIDI:49: error: 'app_timer_id_t' does not name a type

 static app_timer_id_t                   m_uart_rx_id;

```
    ^
```

nRF51822-BLEMIDI:50: error: 'app_timer_id_t' does not name a type

 static app_timer_id_t                   m_status_check_id;

```
    ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void m_uart_rx_handle(void*)':

nRF51822-BLEMIDI:121: error: 'class GattCharacteristic' has no member named 'getHandle'

```
 ble.updateCharacteristicValue(txCharacteristic.getHandle(), rx_buf, bufInc);

                                                ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void disconnectionCallback()':

nRF51822-BLEMIDI:221: error: 'm_uart_rx_id' was not declared in this scope

   err_code = app_timer_stop(m_uart_rx_id);

```
                         ^
```

nRF51822-BLEMIDI:221: error: 'app_timer_stop' was not declared in this scope

   err_code = app_timer_stop(m_uart_rx_id);

```
                                     ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void connectionCallback()':

nRF51822-BLEMIDI:236: error: 'm_uart_rx_id' was not declared in this scope

   err_code = app_timer_create(&m_uart_rx_id, APP_TIMER_MODE_REPEATED, m_uart_rx_handle);

```
                            ^
```

nRF51822-BLEMIDI:236: error: 'APP_TIMER_MODE_REPEATED' was not declared in this scope

   err_code = app_timer_create(&m_uart_rx_id, APP_TIMER_MODE_REPEATED, m_uart_rx_handle);

```
                                          ^
```

nRF51822-BLEMIDI:236: error: 'app_timer_create' was not declared in this scope

   err_code = app_timer_create(&m_uart_rx_id, APP_TIMER_MODE_REPEATED, m_uart_rx_handle);

```
                                                                                   ^
```

nRF51822-BLEMIDI:44: error: 'APP_TIMER_TICKS' was not declared in this scope

 #define STATUS_CHECK_TIME               APP_TIMER_TICKS(20, 0)

```
                                                          ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:238:44: note: in expansion of macro 'STATUS_CHECK_TIME'

   err_code = app_timer_start(m_uart_rx_id, STATUS_CHECK_TIME, NULL);

```
                                        ^
```

nRF51822-BLEMIDI:238: error: 'app_timer_start' was not declared in this scope

   err_code = app_timer_start(m_uart_rx_id, STATUS_CHECK_TIME, NULL);

```
                                                               ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void onDataWritten(uint16_t)':

nRF51822-BLEMIDI:250: error: 'class GattCharacteristic' has no member named 'getHandle'

   if (charHandle == txCharacteristic.getHandle())

```
                                  ^
```

nRF51822-BLEMIDI:252: error: 'class GattCharacteristic' has no member named 'getHandle'

```
 ble.readCharacteristicValue(txCharacteristic.getHandle(), buf, &bytesRead);

                                              ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void setup()':

nRF51822-BLEMIDI:268: error: 'uart_callback_t' was not declared in this scope

   uart_callback_t uart_cb;

   ^

nRF51822-BLEMIDI:268: error: expected ';' before 'uart_cb'

   uart_callback_t uart_cb;

```
               ^
```

nRF51822-BLEMIDI:282: error: invalid conversion from 'void (_)()' to 'Gap::DisconnectionEventCallback_t {aka void (_)(short unsigned int, Gap::DisconnectionReason_t)}' [-fpermissive]

   ble.onDisconnection(disconnectionCallback);

```
                                        ^
```

In file included from C:\Users\administrateur1\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.4\cores\RBL_nRF51822/BLE_API.h:5:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:27:
```

C:\Users\administrateur1\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.4/cores/RBL_nRF51822/BLE_API-master/ble/BLE.h:1089:10: error:   initializing argument 1 of 'void BLE::onDisconnection(Gap::DisconnectionEventCallback_t)' [-fpermissive]

```
 void onDisconnection(Gap::DisconnectionEventCallback_t disconnectionCallback) {

      ^
```

nRF51822-BLEMIDI:283: error: invalid conversion from 'void (_)()' to 'Gap::ConnectionEventCallback_t {aka void (_)(const Gap::ConnectionCallbackParams_t*)}' [-fpermissive]

   ble.onConnection(connectionCallback);

```
                                  ^
```

In file included from C:\Users\administrateur1\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.4\cores\RBL_nRF51822/BLE_API.h:5:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:27:
```

C:\Users\administrateur1\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.4/cores/RBL_nRF51822/BLE_API-master/ble/BLE.h:1077:10: error:   initializing argument 1 of 'void BLE::onConnection(Gap::ConnectionEventCallback_t)' [-fpermissive]

```
 void onConnection(Gap::ConnectionEventCallback_t connectionCallback) {

      ^
```

nRF51822-BLEMIDI:284: error: invalid conversion from 'void (_)(uint16_t) {aka void (_)(short unsigned int)}' to 'void (_)(const GattWriteCallbackParams_)' [-fpermissive]

   ble.onDataWritten(onDataWritten);

```
                              ^
```

In file included from C:\Users\administrateur1\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.4\cores\RBL_nRF51822/BLE_API.h:5:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:27:
```

C:\Users\administrateur1\AppData\Local\Arduino15\packages\RedBearLab\hardware\nRF51822\1.0.4/cores/RBL_nRF51822/BLE_API-master/ble/BLE.h:1176:10: error:   initializing argument 1 of 'void BLE::onDataWritten(void (_)(const GattWriteCallbackParams_))' [-fpermissive]

```
 void onDataWritten(void (*callback)(const GattWriteCallbackParams *eventDataP)) {

      ^
```

nRF51822-BLEMIDI:298: error: expected unqualified-id before '.' token

   SPI.begin();

```
  ^
```

nRF51822-BLEMIDI:300: error: 'RBL_SetDevName' was not declared in this scope

   err_code = RBL_SetDevName("BLIDino");

```
                                  ^
```

nRF51822-BLEMIDI:304: error: 'm_status_check_id' was not declared in this scope

   err_code = app_timer_create(&m_status_check_id, APP_TIMER_MODE_REPEATED, m_status_check_handle);

```
                            ^
```

nRF51822-BLEMIDI:304: error: 'APP_TIMER_MODE_REPEATED' was not declared in this scope

   err_code = app_timer_create(&m_status_check_id, APP_TIMER_MODE_REPEATED, m_status_check_handle);

```
                                               ^
```

nRF51822-BLEMIDI:304: error: 'app_timer_create' was not declared in this scope

   err_code = app_timer_create(&m_status_check_id, APP_TIMER_MODE_REPEATED, m_status_check_handle);

```
                                                                                             ^
```

nRF51822-BLEMIDI:44: error: 'APP_TIMER_TICKS' was not declared in this scope

 #define STATUS_CHECK_TIME               APP_TIMER_TICKS(20, 0)

```
                                                          ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:307:49: note: in expansion of macro 'STATUS_CHECK_TIME'

   err_code = app_timer_start(m_status_check_id, STATUS_CHECK_TIME, NULL);

```
                                             ^
```

nRF51822-BLEMIDI:307: error: 'app_timer_start' was not declared in this scope

   err_code = app_timer_start(m_status_check_id, STATUS_CHECK_TIME, NULL);

```
                                                                    ^
```

exit status 1
'app_timer_id_t' does not name a type

  Ce rapport contiendrait plus d'informations si l'option
  "Montrer les informations de sortie pendant la compilation"
  était activée dans Fichier > Préférences.

**Comment by sieren** [comment]
It looks like the RedBearLab Library isnt installed.
https://github.com/RedBearLab/nRF51822-Arduino

**Comment by Steph77** [comment]
Thanks for your answer !
I think i've installed the library, i successfully compiled exemple in the "nRF_Examples" folder, it's not a sign that all is ok ?
Maybe i've missed a thing... I check the procedure from the begining and i still get this message : 

Arduino : 1.6.7 (Windows 10), Carte : "RBL nRF51822(V1.0 16KB)"

In file included from C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/Usb.h:36:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:30:
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In static member function 'static void SPi<SPI_CLK, SPI_MOSI, SPI_MISO, SPI_SS>::init()':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:57:20: error: expected unqualified-id before '.' token

```
             SPI.begin();

                ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'void MAX3421e<SPI_SS, INTR>::regWr(uint8_t, uint8_t)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:176:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg | 0x02);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:177:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(data);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'uint8_t\* MAX3421e<SPI_SS, INTR>::bytesWr(uint8_t, uint8_t, uint8_t*)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:221:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg | 0x02);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:223:20: error: expected unqualified-id before '.' token

```
             SPI.transfer(*data_p);

                ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'uint8_t MAX3421e<SPI_SS, INTR>::regRd(uint8_t)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:276:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:277:25: error: expected primary-expression before '.' token

```
     uint8_t rv = SPI.transfer(0); // Send empty byte

                     ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h: In member function 'uint8_t\* MAX3421e<SPI_SS, INTR>::bytesRd(uint8_t, uint8_t, uint8_t*)':

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:324:12: error: expected unqualified-id before '.' token

```
     SPI.transfer(reg);

        ^
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\libraries\USB_Host_Shield_2.0-master/usbhost.h:326:28: error: expected primary-expression before '.' token

```
         *data_p++ = SPI.transfer(0);

                        ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: At global scope:

nRF51822-BLEMIDI:49: error: 'app_timer_id_t' does not name a type

 static app_timer_id_t                   m_uart_rx_id;

```
    ^
```

nRF51822-BLEMIDI:50: error: 'app_timer_id_t' does not name a type

 static app_timer_id_t                   m_status_check_id;

```
    ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void m_uart_rx_handle(void*)':

nRF51822-BLEMIDI:121: error: 'class GattCharacteristic' has no member named 'getHandle'

```
 ble.updateCharacteristicValue(txCharacteristic.getHandle(), rx_buf, bufInc);

                                                ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void disconnectionCallback()':

nRF51822-BLEMIDI:221: error: 'm_uart_rx_id' was not declared in this scope

   err_code = app_timer_stop(m_uart_rx_id);

```
                         ^
```

nRF51822-BLEMIDI:221: error: 'app_timer_stop' was not declared in this scope

   err_code = app_timer_stop(m_uart_rx_id);

```
                                     ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void connectionCallback()':

nRF51822-BLEMIDI:236: error: 'm_uart_rx_id' was not declared in this scope

   err_code = app_timer_create(&m_uart_rx_id, APP_TIMER_MODE_REPEATED, m_uart_rx_handle);

```
                            ^
```

nRF51822-BLEMIDI:236: error: 'APP_TIMER_MODE_REPEATED' was not declared in this scope

   err_code = app_timer_create(&m_uart_rx_id, APP_TIMER_MODE_REPEATED, m_uart_rx_handle);

```
                                          ^
```

nRF51822-BLEMIDI:236: error: 'app_timer_create' was not declared in this scope

   err_code = app_timer_create(&m_uart_rx_id, APP_TIMER_MODE_REPEATED, m_uart_rx_handle);

```
                                                                                   ^
```

nRF51822-BLEMIDI:44: error: 'APP_TIMER_TICKS' was not declared in this scope

 #define STATUS_CHECK_TIME               APP_TIMER_TICKS(20, 0)

```
                                                          ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:238:44: note: in expansion of macro 'STATUS_CHECK_TIME'

   err_code = app_timer_start(m_uart_rx_id, STATUS_CHECK_TIME, NULL);

```
                                        ^
```

nRF51822-BLEMIDI:238: error: 'app_timer_start' was not declared in this scope

   err_code = app_timer_start(m_uart_rx_id, STATUS_CHECK_TIME, NULL);

```
                                                               ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void onDataWritten(uint16_t)':

nRF51822-BLEMIDI:250: error: 'class GattCharacteristic' has no member named 'getHandle'

   if (charHandle == txCharacteristic.getHandle())

```
                                  ^
```

nRF51822-BLEMIDI:252: error: 'class GattCharacteristic' has no member named 'getHandle'

```
 ble.readCharacteristicValue(txCharacteristic.getHandle(), buf, &bytesRead);

                                              ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino: In function 'void setup()':

nRF51822-BLEMIDI:268: error: 'uart_callback_t' was not declared in this scope

   uart_callback_t uart_cb;

   ^

nRF51822-BLEMIDI:268: error: expected ';' before 'uart_cb'

   uart_callback_t uart_cb;

```
               ^
```

nRF51822-BLEMIDI:282: error: invalid conversion from 'void (_)()' to 'Gap::DisconnectionEventCallback_t {aka void (_)(short unsigned int, Gap::DisconnectionReason_t)}' [-fpermissive]

   ble.onDisconnection(disconnectionCallback);

```
                                        ^
```

In file included from C:\Users\administrateur1\Bureau\arduino-1.6.7\hardware\RBL\RBL_nRF51822\cores\RBL_nRF51822/BLE_API.h:5:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:27:
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\hardware\RBL\RBL_nRF51822/cores/RBL_nRF51822/BLE_API-master/ble/BLE.h:1089:10: error:   initializing argument 1 of 'void BLE::onDisconnection(Gap::DisconnectionEventCallback_t)' [-fpermissive]

```
 void onDisconnection(Gap::DisconnectionEventCallback_t disconnectionCallback) {

      ^
```

nRF51822-BLEMIDI:283: error: invalid conversion from 'void (_)()' to 'Gap::ConnectionEventCallback_t {aka void (_)(const Gap::ConnectionCallbackParams_t*)}' [-fpermissive]

   ble.onConnection(connectionCallback);

```
                                  ^
```

In file included from C:\Users\administrateur1\Bureau\arduino-1.6.7\hardware\RBL\RBL_nRF51822\cores\RBL_nRF51822/BLE_API.h:5:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:27:
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\hardware\RBL\RBL_nRF51822/cores/RBL_nRF51822/BLE_API-master/ble/BLE.h:1077:10: error:   initializing argument 1 of 'void BLE::onConnection(Gap::ConnectionEventCallback_t)' [-fpermissive]

```
 void onConnection(Gap::ConnectionEventCallback_t connectionCallback) {

      ^
```

nRF51822-BLEMIDI:284: error: invalid conversion from 'void (_)(uint16_t) {aka void (_)(short unsigned int)}' to 'void (_)(const GattWriteCallbackParams_)' [-fpermissive]

   ble.onDataWritten(onDataWritten);

```
                              ^
```

In file included from C:\Users\administrateur1\Bureau\arduino-1.6.7\hardware\RBL\RBL_nRF51822\cores\RBL_nRF51822/BLE_API.h:5:0,

```
             from C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:27:
```

C:\Users\administrateur1\Bureau\arduino-1.6.7\hardware\RBL\RBL_nRF51822/cores/RBL_nRF51822/BLE_API-master/ble/BLE.h:1176:10: error:   initializing argument 1 of 'void BLE::onDataWritten(void (_)(const GattWriteCallbackParams_))' [-fpermissive]

```
 void onDataWritten(void (*callback)(const GattWriteCallbackParams *eventDataP)) {

      ^
```

nRF51822-BLEMIDI:298: error: expected unqualified-id before '.' token

   SPI.begin();

```
  ^
```

nRF51822-BLEMIDI:300: error: 'RBL_SetDevName' was not declared in this scope

   err_code = RBL_SetDevName("BLIDino");

```
                                  ^
```

nRF51822-BLEMIDI:304: error: 'm_status_check_id' was not declared in this scope

   err_code = app_timer_create(&m_status_check_id, APP_TIMER_MODE_REPEATED, m_status_check_handle);

```
                            ^
```

nRF51822-BLEMIDI:304: error: 'APP_TIMER_MODE_REPEATED' was not declared in this scope

   err_code = app_timer_create(&m_status_check_id, APP_TIMER_MODE_REPEATED, m_status_check_handle);

```
                                               ^
```

nRF51822-BLEMIDI:304: error: 'app_timer_create' was not declared in this scope

   err_code = app_timer_create(&m_status_check_id, APP_TIMER_MODE_REPEATED, m_status_check_handle);

```
                                                                                             ^
```

nRF51822-BLEMIDI:44: error: 'APP_TIMER_TICKS' was not declared in this scope

 #define STATUS_CHECK_TIME               APP_TIMER_TICKS(20, 0)

```
                                                          ^
```

C:\Users\administrateur1\Bureau\blidino-master\nRF51822-BLEMIDI\nRF51822-BLEMIDI.ino:307:49: note: in expansion of macro 'STATUS_CHECK_TIME'

   err_code = app_timer_start(m_status_check_id, STATUS_CHECK_TIME, NULL);

```
                                             ^
```

nRF51822-BLEMIDI:307: error: 'app_timer_start' was not declared in this scope

   err_code = app_timer_start(m_status_check_id, STATUS_CHECK_TIME, NULL);

```
                                                                    ^
```

exit status 1
'app_timer_id_t' does not name a type

  Ce rapport contiendrait plus d'informations si l'option
  "Montrer les informations de sortie pendant la compilation"
  était activée dans Fichier > Préférences.

**Comment by sieren** [comment]
You're right, this seems to be a regression introduced by RedBearLabs and thus broke USB_Host_Shield_2.0... I'll see if I can provide a fix.

**Comment by Steph77** [comment]
Thank you for your kindness !
It would be great if you can make it work again, we're working on a musical wall with my student and it would be fun if we can have Midi over bluetooth.

**Comment by sieren** [comment]
I filed an issue with RedBearLabs to see the reasoning behind those changes (foremost removing SPI.h which USB Host Shield 2.0 and ultimately my tool relies on):
https://github.com/RedBearLab/nRF51822-Arduino/issues/50

**Comment by Steph77** [comment]
I hope the problem will be solved. Do you have an older version of the librairy ? It can help me until a solution will be found.

**Comment by sieren** [comment]
For now try using Arduino IDE 1.6.0 and get the RBL Library with a commit from before October last year..

**Comment by Steph77** [comment]
I take arduino 1.6.0 and a version from July 2015, and now i get this message : 

Arduino : 1.6.0 (Windows 8), Carte : "RBL nRF51822"

Cannot run program "{runtime.tools.arm-none-eabi-gcc.path}/bin/arm-none-eabi-g++": CreateProcess error=2, Le fichier spécifié est introuvable

  Ce rapport contiendrait plus d'informations si l'option
  "Montrer les informations de sortie pendant la compilation"
  était activée dans Fichier > Préférences.

Did i forget something ?
Thank you !

**Comment by sieren** [comment]
You forgot to translate it ;)

Looks like it cant find the compiler, must be the settings in there. Try using a slightly newer version, too.. like 1.6.4 or something.

**Comment by Steph77** [comment]
Good news ! I have ccompile successfully with an older version of the library and Arduino 1.6.4.
My redbearlab Card is at work, i'll try to program it on monday if i have time.

Thanks for your help, I hope I will not need it again :)

Bye

**Comment by sieren** [comment]
Glad to hear!
I added it to the known issues list in the readme and will do some further investigation later on (since this needs to be fixed at some point).

Thanks for making me aware!

**Comment by Steph77** [comment]
Hi,
sorry to distrub you again but i still have a little problem...

I programed my redbearlab nRF51822's card with success.

But i can't see it as a bluetooth device with my Ipad air 2 (IOS9.2.1).
I try to see it in setting, bluetooth menu and with your app :midimittr

Do you have any idea or test to find the problem  ? Can it be the nrf card ?

Thanks for your help !

Stéphane

**Comment by sieren** [comment]
You might need to downgrade the Device Firmware to S100 by placing the S100 hex file onto the mbed drive of the nRF Board

**Comment by Steph77** [comment]
i found S110.hex here : https://www.nordicsemi.com/eng/Products/Bluetooth-Smart-Bluetooth-low-energy/nRF51822
but where can i find S100.hex ?

**Comment by sieren** [comment]
Sorry, S110 is correct

**Comment by Steph77** [comment]
Finally  my arduino piano works perfectly with BLIDINO!
Thank you so much !

**Comment by sieren** [comment]
Glad to hear!! :) Enjoy! :)

**Comment by sieren** [comment]
FYI: https://github.com/sieren/blidino/pull/8
